#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = waybar & hyprpaper & firefox


# needed for waybar status
exec-once = nm-applet --indicator &
exec-once = blueman-applet &
# wallpaper image
exec-once = swaybg --image ~/.config/sway/wallpapers/milkyway.png --mode fill
# swayidle
exec-once = $HOME/.config/hypr/scripts/swayidle.sh
# start polkit agent
exec-once = systemctl --user start hyprpolkitagent

# start waybar
exec = $HOME/.config/hypr/scripts/startup.sh

# start clipboard manager
# https://github.com/sentriz/cliphist
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
