#!/bin/bash
if [[ "$@" == *"clone git@"* ]]; then
  echo "WARNING : DO NOT FORGET TO CONFIGURE YOUR GIT IDENTITY"
  read -p "" NULL
elif [[ "$@" == *"git commit"* && ! $(git config --local -l |grep user.signingkey) ]]; then
  echo "WARNING : SIGNINGKEY IS NOT CONFIGURED"
  read -p "" NULL
elif [[ "$@" == *"git commit"* && "$@" != *" -S "* && $(git config --local -l |grep user.signingkey) ]]; then
  echo "WARNING : SIGNINGKEY IS CONFIGURED AND YOU'RE NOT USING IT"
  read -p "" NULL
fi
/usr/bin/git "$@"
